export type ApiAuthLevel = 'public' | 'auth' | 'role' | 'middleware';

export interface ApiEndpoint {
  path: string;
  methods: string[];
  auth: ApiAuthLevel;
  group: string;
  note?: string;
}

export const API_DOC_HOST = 'https://ai.rhautt.com';

export const API_AUTH_LABELS: Record<ApiAuthLevel, string> = {
  public: '公开/协议',
  auth: '登录态',
  role: '角色权限',
  middleware: '中间件保护',
};

export const API_AUTH_DESCRIPTIONS: Record<ApiAuthLevel, string> = {
  public: '公开白名单或协议端点，不依赖 Tandem 登录 Cookie；协议端点可能使用自身鉴权。',
  auth: '路由内显式调用 requireAuth，需要有效 tandem_at 登录 Cookie。',
  role: '需要登录态，并显式调用 requireRole 或角色守卫。',
  middleware: '路由内未显式调用 requireAuth，但不在公开白名单内，仍会被 middleware 登录态保护。',
};

export const API_GROUPS = [
  '认证与账号',
  '管理后台',
  '个人与组织',
  'OKR、KPI 与绩效',
  '协作、IM 与日程',
  '文档、知识库与网盘',
  'AI、Agent 与技能',
  '学习、Persona 与记忆',
  '邮件、内网、治理与审计',
  '平台、状态、推送与协议',
] as const;

export const API_ENDPOINTS: ApiEndpoint[] = [
  { group: '认证与账号', path: '/api/auth/apply', methods: ['POST'], auth: 'public' },
  { group: '认证与账号', path: '/api/auth/change-password', methods: ['POST'], auth: 'public' },
  { group: '认证与账号', path: '/api/auth/invite', methods: ['GET', 'POST'], auth: 'public' },
  { group: '认证与账号', path: '/api/auth/login', methods: ['POST'], auth: 'public', note: '成功后写入 tandem_at；可能同时写入 tandem_rt。' },
  { group: '认证与账号', path: '/api/auth/logout', methods: ['POST'], auth: 'public' },
  { group: '认证与账号', path: '/api/auth/me', methods: ['GET'], auth: 'public', note: '读取当前登录用户；内部仍会尝试会话解析。' },
  { group: '认证与账号', path: '/api/auth/mfa/setup', methods: ['GET', 'POST'], auth: 'public' },
  { group: '认证与账号', path: '/api/auth/mfa/verify', methods: ['POST'], auth: 'public' },
  { group: '认证与账号', path: '/api/auth/phone/send-code', methods: ['POST'], auth: 'public' },
  { group: '认证与账号', path: '/api/auth/phone/verify', methods: ['POST'], auth: 'public' },
  { group: '认证与账号', path: '/api/auth/register', methods: ['POST'], auth: 'public' },
  { group: '认证与账号', path: '/api/auth/sso-register', methods: ['POST'], auth: 'public' },
  { group: '认证与账号', path: '/api/auth/wechat/poll', methods: ['GET'], auth: 'public' },
  { group: '认证与账号', path: '/api/auth/wechat/qr', methods: ['GET'], auth: 'public' },

  { group: '管理后台', path: '/api/admin/ai-settings', methods: ['GET', 'PUT'], auth: 'auth' },
  { group: '管理后台', path: '/api/admin/company-brain', methods: ['GET'], auth: 'auth' },
  { group: '管理后台', path: '/api/admin/company-brain/decisions', methods: ['GET'], auth: 'role' },
  { group: '管理后台', path: '/api/admin/company-brain/metrics', methods: ['GET'], auth: 'role' },
  { group: '管理后台', path: '/api/admin/company-brain/reflection', methods: ['GET', 'PATCH', 'POST'], auth: 'role' },
  { group: '管理后台', path: '/api/admin/company-brain/reflection/proposal', methods: ['PATCH'], auth: 'role' },
  { group: '管理后台', path: '/api/admin/evals', methods: ['GET', 'POST'], auth: 'role' },
  { group: '管理后台', path: '/api/admin/governance/okr-drift', methods: ['GET'], auth: 'role' },
  { group: '管理后台', path: '/api/admin/organizations', methods: ['GET', 'POST'], auth: 'role' },
  { group: '管理后台', path: '/api/admin/organizations/{id}/invite', methods: ['POST'], auth: 'role' },
  { group: '管理后台', path: '/api/admin/organizations/{id}/suspend', methods: ['POST'], auth: 'role' },
  { group: '管理后台', path: '/api/admin/personas', methods: ['GET'], auth: 'role' },
  { group: '管理后台', path: '/api/admin/personas/{userId}', methods: ['PATCH'], auth: 'role' },
  { group: '管理后台', path: '/api/admin/seed-ruihe', methods: ['POST'], auth: 'role' },
  { group: '管理后台', path: '/api/admin/skill-evals', methods: ['GET'], auth: 'role' },
  { group: '管理后台', path: '/api/admin/skill-proposals', methods: ['GET', 'PATCH', 'POST'], auth: 'role' },
  { group: '管理后台', path: '/api/admin/skills/reload', methods: ['GET', 'POST'], auth: 'auth' },
  { group: '管理后台', path: '/api/admin/user-applications', methods: ['GET'], auth: 'role' },
  { group: '管理后台', path: '/api/admin/user-applications/{id}/approve', methods: ['POST'], auth: 'role' },
  { group: '管理后台', path: '/api/admin/user-applications/{id}/reject', methods: ['POST'], auth: 'role' },
  { group: '管理后台', path: '/api/admin/users/{id}/anonymize', methods: ['POST'], auth: 'middleware' },
  { group: '管理后台', path: '/api/admin/users/bulk-invite', methods: ['POST'], auth: 'middleware' },
  { group: '管理后台', path: '/api/admin/users/bulk-invite/template', methods: ['GET'], auth: 'middleware' },

  { group: '个人与组织', path: '/api/me/brief-options', methods: ['GET'], auth: 'auth' },
  { group: '个人与组织', path: '/api/me/dashboard', methods: ['GET'], auth: 'auth' },
  { group: '个人与组织', path: '/api/me/expert-panel', methods: ['POST'], auth: 'auth' },
  { group: '个人与组织', path: '/api/me/export', methods: ['GET'], auth: 'middleware' },
  { group: '个人与组织', path: '/api/me/okr-health', methods: ['GET'], auth: 'auth' },
  { group: '个人与组织', path: '/api/me/portfolio', methods: ['GET'], auth: 'auth' },
  { group: '个人与组织', path: '/api/me/retro-pending', methods: ['GET'], auth: 'auth' },
  { group: '个人与组织', path: '/api/org/departments', methods: ['GET', 'POST'], auth: 'auth' },
  { group: '个人与组织', path: '/api/org/departments/{id}', methods: ['DELETE', 'PATCH'], auth: 'auth' },
  { group: '个人与组织', path: '/api/org/users', methods: ['GET'], auth: 'auth' },
  { group: '个人与组织', path: '/api/org/users/{id}', methods: ['PATCH'], auth: 'auth' },
  { group: '个人与组织', path: '/api/org/users/import', methods: ['POST'], auth: 'auth' },
  { group: '个人与组织', path: '/api/org/users/import/template', methods: ['GET'], auth: 'middleware' },
  { group: '个人与组织', path: '/api/teammates', methods: ['GET'], auth: 'auth' },

  { group: 'OKR、KPI 与绩效', path: '/api/1on1', methods: ['GET', 'POST'], auth: 'auth' },
  { group: 'OKR、KPI 与绩效', path: '/api/1on1/{id}', methods: ['DELETE', 'GET', 'PATCH'], auth: 'auth' },
  { group: 'OKR、KPI 与绩效', path: '/api/1on1/{id}/action-items', methods: ['POST'], auth: 'auth' },
  { group: 'OKR、KPI 与绩效', path: '/api/1on1/action-items/{id}', methods: ['DELETE', 'PATCH'], auth: 'auth' },
  { group: 'OKR、KPI 与绩效', path: '/api/360/cycles', methods: ['GET', 'POST'], auth: 'role' },
  { group: 'OKR、KPI 与绩效', path: '/api/360/cycles/{id}', methods: ['PATCH'], auth: 'auth' },
  { group: 'OKR、KPI 与绩效', path: '/api/360/cycles/{id}/assignments', methods: ['GET', 'POST'], auth: 'auth' },
  { group: 'OKR、KPI 与绩效', path: '/api/360/submissions', methods: ['GET', 'POST'], auth: 'auth' },
  { group: 'OKR、KPI 与绩效', path: '/api/kpi', methods: ['GET', 'POST'], auth: 'auth' },
  { group: 'OKR、KPI 与绩效', path: '/api/kpi/{id}', methods: ['DELETE', 'GET', 'PATCH'], auth: 'auth' },
  { group: 'OKR、KPI 与绩效', path: '/api/kpi/analytics', methods: ['GET'], auth: 'auth' },
  { group: 'OKR、KPI 与绩效', path: '/api/kpi/causal-links', methods: ['GET', 'POST'], auth: 'auth' },
  { group: 'OKR、KPI 与绩效', path: '/api/kpi/causal-links/{id}', methods: ['DELETE', 'PATCH'], auth: 'auth' },
  { group: 'OKR、KPI 与绩效', path: '/api/kpi/cycles', methods: ['GET', 'POST'], auth: 'auth' },
  { group: 'OKR、KPI 与绩效', path: '/api/kpi/cycles/{id}', methods: ['DELETE', 'GET', 'PATCH'], auth: 'auth' },
  { group: 'OKR、KPI 与绩效', path: '/api/kpi/cycles/{id}/bonus', methods: ['GET', 'POST'], auth: 'auth' },
  { group: 'OKR、KPI 与绩效', path: '/api/kpi/cycles/{id}/close', methods: ['POST'], auth: 'auth' },
  { group: 'OKR、KPI 与绩效', path: '/api/kpi/erp/sync', methods: ['POST'], auth: 'auth' },
  { group: 'OKR、KPI 与绩效', path: '/api/kpi/export', methods: ['GET'], auth: 'auth' },
  { group: 'OKR、KPI 与绩效', path: '/api/kpi/import', methods: ['POST'], auth: 'auth' },
  { group: 'OKR、KPI 与绩效', path: '/api/kpi/manual-entry', methods: ['GET', 'POST'], auth: 'auth' },
  { group: 'OKR、KPI 与绩效', path: '/api/kpi/seed-demo', methods: ['POST'], auth: 'role' },
  { group: 'OKR、KPI 与绩效', path: '/api/kpi/snapshots', methods: ['GET', 'POST'], auth: 'role' },
  { group: 'OKR、KPI 与绩效', path: '/api/kpi/subjects', methods: ['GET', 'POST'], auth: 'auth' },
  { group: 'OKR、KPI 与绩效', path: '/api/kpi/subjects/{id}', methods: ['DELETE', 'GET', 'PATCH'], auth: 'auth' },
  { group: 'OKR、KPI 与绩效', path: '/api/kpi/subjects/export', methods: ['GET'], auth: 'auth' },
  { group: 'OKR、KPI 与绩效', path: '/api/kpi/subjects/import', methods: ['POST'], auth: 'auth' },
  { group: 'OKR、KPI 与绩效', path: '/api/nine-box', methods: ['GET'], auth: 'auth' },
  { group: 'OKR、KPI 与绩效', path: '/api/nine-box/suggestions', methods: ['GET'], auth: 'role' },
  { group: 'OKR、KPI 与绩效', path: '/api/okr/bulk-create/options', methods: ['POST'], auth: 'auth' },
  { group: 'OKR、KPI 与绩效', path: '/api/okr/checkins', methods: ['GET', 'POST'], auth: 'auth' },
  { group: 'OKR、KPI 与绩效', path: '/api/okr/cycles/{id}/activate', methods: ['POST'], auth: 'auth' },
  { group: 'OKR、KPI 与绩效', path: '/api/okr/initiatives', methods: ['GET', 'POST'], auth: 'auth' },
  { group: 'OKR、KPI 与绩效', path: '/api/okr/initiatives/{id}', methods: ['DELETE', 'PATCH'], auth: 'auth' },
  { group: 'OKR、KPI 与绩效', path: '/api/okr/key-results', methods: ['POST'], auth: 'auth' },
  { group: 'OKR、KPI 与绩效', path: '/api/okr/key-results/{id}', methods: ['DELETE', 'PATCH'], auth: 'auth' },
  { group: 'OKR、KPI 与绩效', path: '/api/tandem-okr', methods: ['GET', 'POST'], auth: 'auth' },
  { group: 'OKR、KPI 与绩效', path: '/api/tandem-okr/{id}', methods: ['DELETE', 'PATCH'], auth: 'auth' },
  { group: 'OKR、KPI 与绩效', path: '/api/tti', methods: ['GET', 'POST'], auth: 'auth' },

  { group: '协作、IM 与日程', path: '/api/calendar', methods: ['GET', 'POST'], auth: 'auth' },
  { group: '协作、IM 与日程', path: '/api/calendar/{id}/invite', methods: ['POST'], auth: 'middleware' },
  { group: '协作、IM 与日程', path: '/api/calendar/meeting-prep', methods: ['POST'], auth: 'auth' },
  { group: '协作、IM 与日程', path: '/api/calendar/meeting-retro', methods: ['POST'], auth: 'auth' },
  { group: '协作、IM 与日程', path: '/api/calendar/nlp-create', methods: ['POST'], auth: 'auth' },
  { group: '协作、IM 与日程', path: '/api/calendar/smart-time', methods: ['POST'], auth: 'auth' },
  { group: '协作、IM 与日程', path: '/api/im/channels', methods: ['GET', 'POST'], auth: 'auth' },
  { group: '协作、IM 与日程', path: '/api/im/channels/{id}', methods: ['DELETE', 'GET', 'PATCH', 'PUT'], auth: 'auth' },
  { group: '协作、IM 与日程', path: '/api/im/channels/{id}/agent-mode', methods: ['PATCH'], auth: 'auth' },
  { group: '协作、IM 与日程', path: '/api/im/channels/{id}/members', methods: ['DELETE', 'GET', 'PATCH', 'POST'], auth: 'auth' },
  { group: '协作、IM 与日程', path: '/api/im/channels/{id}/messages', methods: ['GET', 'POST'], auth: 'auth' },
  { group: '协作、IM 与日程', path: '/api/im/channels/{id}/pins', methods: ['POST'], auth: 'auth' },
  { group: '协作、IM 与日程', path: '/api/im/channels/{id}/read', methods: ['POST'], auth: 'auth' },
  { group: '协作、IM 与日程', path: '/api/im/channels/{id}/stream', methods: ['GET'], auth: 'auth' },
  { group: '协作、IM 与日程', path: '/api/im/channels/{id}/summary', methods: ['POST'], auth: 'auth' },
  { group: '协作、IM 与日程', path: '/api/im/channels/seed-from-org', methods: ['POST'], auth: 'role' },
  { group: '协作、IM 与日程', path: '/api/im/dm', methods: ['POST'], auth: 'auth' },
  { group: '协作、IM 与日程', path: '/api/im/messages/{id}', methods: ['PATCH'], auth: 'auth' },
  { group: '协作、IM 与日程', path: '/api/im/messages/{id}/ai-trace', methods: ['GET'], auth: 'auth' },
  { group: '协作、IM 与日程', path: '/api/im/messages/{id}/promote-to-memory', methods: ['POST'], auth: 'auth' },
  { group: '协作、IM 与日程', path: '/api/im/messages/{id}/reactions', methods: ['POST'], auth: 'auth' },
  { group: '协作、IM 与日程', path: '/api/im/messages/{id}/spawn-room', methods: ['POST'], auth: 'auth' },
  { group: '协作、IM 与日程', path: '/api/meetings/bookings', methods: ['GET', 'POST'], auth: 'auth' },
  { group: '协作、IM 与日程', path: '/api/meetings/livekit-token', methods: ['POST'], auth: 'auth' },
  { group: '协作、IM 与日程', path: '/api/meetings/rooms', methods: ['GET'], auth: 'middleware' },
  { group: '协作、IM 与日程', path: '/api/notifications', methods: ['GET', 'POST'], auth: 'auth' },
  { group: '协作、IM 与日程', path: '/api/notifications/{id}', methods: ['DELETE', 'GET', 'PATCH'], auth: 'middleware' },
  { group: '协作、IM 与日程', path: '/api/notifications/badge', methods: ['GET'], auth: 'auth' },
  { group: '协作、IM 与日程', path: '/api/realtime', methods: ['POST'], auth: 'middleware' },
  { group: '协作、IM 与日程', path: '/api/realtime/{channel}', methods: ['GET'], auth: 'middleware' },

  { group: '文档、知识库与网盘', path: '/api/bitable/seed-templates', methods: ['POST'], auth: 'auth' },
  { group: '文档、知识库与网盘', path: '/api/bitable/tables', methods: ['GET', 'POST'], auth: 'auth' },
  { group: '文档、知识库与网盘', path: '/api/bitable/tables/{id}', methods: ['DELETE', 'GET', 'PATCH'], auth: 'auth' },
  { group: '文档、知识库与网盘', path: '/api/bitable/tables/{id}/rows', methods: ['PATCH', 'POST'], auth: 'auth' },
  { group: '文档、知识库与网盘', path: '/api/bitable/tables/{id}/rows/{rowId}/compute-ai', methods: ['POST'], auth: 'auth' },
  { group: '文档、知识库与网盘', path: '/api/documents', methods: ['GET', 'POST'], auth: 'auth' },
  { group: '文档、知识库与网盘', path: '/api/documents/{id}', methods: ['DELETE', 'GET', 'PATCH', 'PUT'], auth: 'auth' },
  { group: '文档、知识库与网盘', path: '/api/documents/{id}/permissions', methods: ['PATCH'], auth: 'auth' },
  { group: '文档、知识库与网盘', path: '/api/documents/{id}/promote-to-memory', methods: ['POST'], auth: 'auth' },
  { group: '文档、知识库与网盘', path: '/api/documents/{id}/review', methods: ['POST'], auth: 'auth' },
  { group: '文档、知识库与网盘', path: '/api/documents/{id}/spawned-decision-card', methods: ['PATCH'], auth: 'auth' },
  { group: '文档、知识库与网盘', path: '/api/documents/{id}/yjs-info', methods: ['GET'], auth: 'auth' },
  { group: '文档、知识库与网盘', path: '/api/drive', methods: ['GET', 'POST'], auth: 'auth' },
  { group: '文档、知识库与网盘', path: '/api/drive/breadcrumbs', methods: ['GET'], auth: 'auth' },
  { group: '文档、知识库与网盘', path: '/api/drive/presign', methods: ['POST'], auth: 'auth' },
  { group: '文档、知识库与网盘', path: '/api/knowledge', methods: ['GET', 'POST'], auth: 'auth' },
  { group: '文档、知识库与网盘', path: '/api/knowledge/{id}', methods: ['DELETE', 'PATCH'], auth: 'auth' },
  { group: '文档、知识库与网盘', path: '/api/knowledge/web-ingest', methods: ['POST'], auth: 'auth' },

  { group: 'AI、Agent 与技能', path: '/api/agent/intent', methods: ['POST'], auth: 'auth' },
  { group: 'AI、Agent 与技能', path: '/api/agent/spawn', methods: ['POST'], auth: 'auth' },
  { group: 'AI、Agent 与技能', path: '/api/agent/specialists', methods: ['GET', 'POST'], auth: 'auth' },
  { group: 'AI、Agent 与技能', path: '/api/agent/wait', methods: ['POST'], auth: 'middleware' },
  { group: 'AI、Agent 与技能', path: '/api/agent-skills', methods: ['GET'], auth: 'auth' },
  { group: 'AI、Agent 与技能', path: '/api/ai/extract-daily-report', methods: ['POST'], auth: 'auth' },
  { group: 'AI、Agent 与技能', path: '/api/ai/persona-train', methods: ['POST'], auth: 'auth' },
  { group: 'AI、Agent 与技能', path: '/api/ai/weekly-recap', methods: ['POST'], auth: 'auth' },
  { group: 'AI、Agent 与技能', path: '/api/boss-ai/stream', methods: ['GET', 'POST'], auth: 'auth' },
  { group: 'AI、Agent 与技能', path: '/api/company-brain/by-message/{messageId}', methods: ['GET'], auth: 'auth' },
  { group: 'AI、Agent 与技能', path: '/api/company-brain/feedback', methods: ['POST'], auth: 'auth' },
  { group: 'AI、Agent 与技能', path: '/api/llm-stream', methods: ['POST'], auth: 'middleware' },
  { group: 'AI、Agent 与技能', path: '/api/skills', methods: ['GET'], auth: 'auth' },
  { group: 'AI、Agent 与技能', path: '/api/skills/governance', methods: ['GET', 'POST'], auth: 'auth' },
  { group: 'AI、Agent 与技能', path: '/api/tandem-skills', methods: ['GET'], auth: 'auth' },
  { group: 'AI、Agent 与技能', path: '/api/tandem-skills/execute', methods: ['POST'], auth: 'auth' },
  { group: 'AI、Agent 与技能', path: '/api/workflows/run', methods: ['POST'], auth: 'auth' },

  { group: '学习、Persona 与记忆', path: '/api/learning/certifications', methods: ['GET'], auth: 'auth' },
  { group: '学习、Persona 与记忆', path: '/api/learning/complete', methods: ['POST'], auth: 'auth' },
  { group: '学习、Persona 与记忆', path: '/api/learning/generate', methods: ['POST'], auth: 'role' },
  { group: '学习、Persona 与记忆', path: '/api/learning/lessons', methods: ['GET', 'POST'], auth: 'role' },
  { group: '学习、Persona 与记忆', path: '/api/learning/lessons/{id}', methods: ['DELETE', 'GET', 'PATCH'], auth: 'role' },
  { group: '学习、Persona 与记忆', path: '/api/learning/progress', methods: ['GET'], auth: 'auth' },
  { group: '学习、Persona 与记忆', path: '/api/memories/promote-text', methods: ['POST'], auth: 'auth' },
  { group: '学习、Persona 与记忆', path: '/api/memory', methods: ['GET'], auth: 'middleware' },
  { group: '学习、Persona 与记忆', path: '/api/persona/{userId}', methods: ['GET', 'PATCH'], auth: 'auth' },
  { group: '学习、Persona 与记忆', path: '/api/persona/{userId}/constitution', methods: ['DELETE', 'GET', 'POST'], auth: 'auth' },
  { group: '学习、Persona 与记忆', path: '/api/persona/{userId}/progress', methods: ['GET'], auth: 'middleware' },
  { group: '学习、Persona 与记忆', path: '/api/persona/{userId}/training-context', methods: ['GET'], auth: 'auth' },
  { group: '学习、Persona 与记忆', path: '/api/persona/me/reflexion-log', methods: ['GET'], auth: 'auth' },
  { group: '学习、Persona 与记忆', path: '/api/persona/proxy-actions', methods: ['GET'], auth: 'auth' },
  { group: '学习、Persona 与记忆', path: '/api/persona/proxy-actions/{id}/confirm', methods: ['POST'], auth: 'auth' },
  { group: '学习、Persona 与记忆', path: '/api/persona/proxy-actions/{id}/feedback', methods: ['POST'], auth: 'auth' },
  { group: '学习、Persona 与记忆', path: '/api/persona/proxy-actions/{id}/veto', methods: ['POST'], auth: 'auth' },
  { group: '学习、Persona 与记忆', path: '/api/shouchao/ask', methods: ['POST'], auth: 'auth' },
  { group: '学习、Persona 与记忆', path: '/api/shouchao/clip', methods: ['POST'], auth: 'auth' },
  { group: '学习、Persona 与记忆', path: '/api/shouchao/import', methods: ['POST'], auth: 'auth' },
  { group: '学习、Persona 与记忆', path: '/api/shouchao/notes', methods: ['GET', 'POST'], auth: 'auth' },
  { group: '学习、Persona 与记忆', path: '/api/shouchao/notes/{id}', methods: ['DELETE', 'GET', 'PATCH'], auth: 'auth' },
  { group: '学习、Persona 与记忆', path: '/api/shouchao/notes/{id}/links', methods: ['GET'], auth: 'auth' },
  { group: '学习、Persona 与记忆', path: '/api/shouchao/notes/{id}/share-to-persona', methods: ['POST'], auth: 'auth' },
  { group: '学习、Persona 与记忆', path: '/api/shouchao/sync', methods: ['GET', 'POST'], auth: 'auth' },
  { group: '学习、Persona 与记忆', path: '/api/shouchao/transcribe', methods: ['POST'], auth: 'auth' },
  { group: '学习、Persona 与记忆', path: '/api/tandem/memory', methods: ['POST'], auth: 'auth' },
  { group: '学习、Persona 与记忆', path: '/api/tandem/memory/{id}', methods: ['DELETE', 'GET', 'PATCH'], auth: 'auth' },
  { group: '学习、Persona 与记忆', path: '/api/tandem/memory/downgrade', methods: ['GET', 'PATCH', 'POST'], auth: 'middleware' },
  { group: '学习、Persona 与记忆', path: '/api/tandem/memory/list', methods: ['GET'], auth: 'middleware' },
  { group: '学习、Persona 与记忆', path: '/api/tandem/memory/promotion', methods: ['GET', 'PATCH', 'POST'], auth: 'middleware' },
  { group: '学习、Persona 与记忆', path: '/api/tandem/persona/upgrade', methods: ['DELETE', 'GET', 'POST'], auth: 'middleware' },

  { group: '邮件、内网、治理与审计', path: '/api/audit', methods: ['GET'], auth: 'auth' },
  { group: '邮件、内网、治理与审计', path: '/api/audit/verify', methods: ['GET'], auth: 'role' },
  { group: '邮件、内网、治理与审计', path: '/api/governance/projects', methods: ['GET', 'POST'], auth: 'role' },
  { group: '邮件、内网、治理与审计', path: '/api/governance/projects/{id}', methods: ['DELETE', 'PATCH'], auth: 'role' },
  { group: '邮件、内网、治理与审计', path: '/api/governance/projects/{id}/links', methods: ['DELETE', 'POST'], auth: 'role' },
  { group: '邮件、内网、治理与审计', path: '/api/governance/projects/{id}/template', methods: ['GET', 'PUT'], auth: 'role' },
  { group: '邮件、内网、治理与审计', path: '/api/governance/projects/{id}/versions', methods: ['GET'], auth: 'auth' },
  { group: '邮件、内网、治理与审计', path: '/api/governance/projects/{id}/versions/rollback', methods: ['POST'], auth: 'role' },
  { group: '邮件、内网、治理与审计', path: '/api/intranet/posts', methods: ['GET', 'POST'], auth: 'role' },
  { group: '邮件、内网、治理与审计', path: '/api/intranet/posts/{id}', methods: ['DELETE', 'GET', 'PATCH'], auth: 'role' },
  { group: '邮件、内网、治理与审计', path: '/api/intranet/posts/{id}/read', methods: ['GET', 'POST'], auth: 'auth' },
  { group: '邮件、内网、治理与审计', path: '/api/intranet/posts/unread', methods: ['GET'], auth: 'auth' },
  { group: '邮件、内网、治理与审计', path: '/api/mail/ai-reply', methods: ['POST'], auth: 'auth' },
  { group: '邮件、内网、治理与审计', path: '/api/mail/ai-review', methods: ['POST'], auth: 'auth' },
  { group: '邮件、内网、治理与审计', path: '/api/mail/attachment', methods: ['GET'], auth: 'auth' },
  { group: '邮件、内网、治理与审计', path: '/api/mail/config', methods: ['GET', 'PUT'], auth: 'auth' },
  { group: '邮件、内网、治理与审计', path: '/api/mail/credentials', methods: ['DELETE', 'GET', 'POST'], auth: 'auth' },
  { group: '邮件、内网、治理与审计', path: '/api/mail/inbox', methods: ['DELETE', 'GET', 'PATCH', 'POST'], auth: 'auth' },
  { group: '邮件、内网、治理与审计', path: '/api/mail/inbox/{uid}', methods: ['GET'], auth: 'auth' },
  { group: '邮件、内网、治理与审计', path: '/api/mail/move', methods: ['POST'], auth: 'auth' },
  { group: '邮件、内网、治理与审计', path: '/api/mail/search', methods: ['GET'], auth: 'auth' },
  { group: '邮件、内网、治理与审计', path: '/api/mail/send', methods: ['POST'], auth: 'auth' },
  { group: '邮件、内网、治理与审计', path: '/api/mail/status', methods: ['GET'], auth: 'auth' },
  { group: '邮件、内网、治理与审计', path: '/api/mail/thread-summary', methods: ['POST'], auth: 'auth' },

  { group: '平台、状态、推送与协议', path: '/.well-known/jwks.json', methods: ['GET'], auth: 'public' },
  { group: '平台、状态、推送与协议', path: '/.well-known/openid-configuration', methods: ['GET'], auth: 'public' },
  { group: '平台、状态、推送与协议', path: '/api/analytics/cross-rollup', methods: ['GET'], auth: 'role' },
  { group: '平台、状态、推送与协议', path: '/api/analytics/okr-kpi-consistency', methods: ['GET'], auth: 'role' },
  { group: '平台、状态、推送与协议', path: '/api/announcements/featured', methods: ['GET'], auth: 'middleware' },
  { group: '平台、状态、推送与协议', path: '/api/budget', methods: ['GET', 'POST'], auth: 'auth' },
  { group: '平台、状态、推送与协议', path: '/api/business-review/monthly', methods: ['GET'], auth: 'auth' },
  { group: '平台、状态、推送与协议', path: '/api/convergence', methods: ['GET', 'POST'], auth: 'auth' },
  { group: '平台、状态、推送与协议', path: '/api/convergence/{id}', methods: ['GET', 'POST'], auth: 'auth' },
  { group: '平台、状态、推送与协议', path: '/api/convergence/{id}/stream', methods: ['GET'], auth: 'auth' },
  { group: '平台、状态、推送与协议', path: '/api/cron', methods: ['GET', 'POST'], auth: 'middleware' },
  { group: '平台、状态、推送与协议', path: '/api/cron/{id}', methods: ['DELETE', 'PATCH', 'POST'], auth: 'middleware' },
  { group: '平台、状态、推送与协议', path: '/api/dashboard/stats', methods: ['GET'], auth: 'auth' },
  { group: '平台、状态、推送与协议', path: '/api/health', methods: ['GET'], auth: 'public', note: 'readiness/liveness 探针。' },
  { group: '平台、状态、推送与协议', path: '/api/integrations/health', methods: ['GET'], auth: 'public' },
  { group: '平台、状态、推送与协议', path: '/api/launchpad', methods: ['GET', 'POST'], auth: 'role' },
  { group: '平台、状态、推送与协议', path: '/api/launchpad/{id}', methods: ['DELETE', 'PATCH', 'POST'], auth: 'role' },
  { group: '平台、状态、推送与协议', path: '/api/launchpad/{id}/click', methods: ['POST'], auth: 'auth' },
  { group: '平台、状态、推送与协议', path: '/api/llm-health', methods: ['GET'], auth: 'public' },
  { group: '平台、状态、推送与协议', path: '/api/logs', methods: ['GET'], auth: 'middleware' },
  { group: '平台、状态、推送与协议', path: '/api/mcp', methods: ['GET'], auth: 'middleware' },
  { group: '平台、状态、推送与协议', path: '/api/oidc/authorize', methods: ['GET'], auth: 'public' },
  { group: '平台、状态、推送与协议', path: '/api/oidc/clients', methods: ['GET', 'POST'], auth: 'role' },
  { group: '平台、状态、推送与协议', path: '/api/oidc/clients/{id}', methods: ['DELETE', 'PATCH'], auth: 'role' },
  { group: '平台、状态、推送与协议', path: '/api/oidc/logout', methods: ['GET'], auth: 'public' },
  { group: '平台、状态、推送与协议', path: '/api/oidc/token', methods: ['POST'], auth: 'public' },
  { group: '平台、状态、推送与协议', path: '/api/oidc/userinfo', methods: ['GET', 'POST'], auth: 'public' },
  { group: '平台、状态、推送与协议', path: '/api/partner/apply', methods: ['POST'], auth: 'middleware' },
  { group: '平台、状态、推送与协议', path: '/api/push/send', methods: ['POST'], auth: 'auth' },
  { group: '平台、状态、推送与协议', path: '/api/push/subscribe', methods: ['DELETE', 'POST'], auth: 'auth' },
  { group: '平台、状态、推送与协议', path: '/api/push/vapid', methods: ['GET'], auth: 'middleware' },
  { group: '平台、状态、推送与协议', path: '/api/settings/llm-preference', methods: ['GET', 'PUT'], auth: 'auth' },
  { group: '平台、状态、推送与协议', path: '/api/settings/tenant-ai-policy', methods: ['GET', 'PUT'], auth: 'auth' },
  { group: '平台、状态、推送与协议', path: '/api/status', methods: ['GET'], auth: 'middleware' },
  { group: '平台、状态、推送与协议', path: '/api/stream', methods: ['POST'], auth: 'middleware' },
];

export const API_DOC_STATS = {
  endpoints: API_ENDPOINTS.length,
  methods: API_ENDPOINTS.reduce((total, endpoint) => total + endpoint.methods.length, 0),
  groups: API_GROUPS.length,
};
