const ROUTE_OWNERSHIP = [
  // 已完成切流的域直接记录 NestJS owner；迁移中的域暂以 nestjsOwner 标记目标实现。
  { prefix: '/api/v2/auth',       owner: 'services/api/src/modules/auth',   status: 'production' },
  { prefix: '/api/v2/tenants',    owner: 'services/api/src/modules/tenant', status: 'production' },
  { prefix: '/api/v2/dealers',    owner: 'services/api/src/modules/tenant', status: 'production' },
  { prefix: '/api/v2/stores',     owner: 'services/api/src/modules/tenant', status: 'production' },
  { prefix: '/api/v2/entitlement', owner: 'services/api/src/modules/entitlement', status: 'production' },
  { prefix: '/api/v2/crm',        owner: 'services/api/src/modules/crm',    status: 'production' },
  { prefix: '/api/v2/audit',      owner: 'server/modules/audit',            status: 'production' },
  { prefix: '/api/v2/brand',      owner: 'services/api/src/modules/brand, services/api/src/modules/product-catalog, and services/api/src/modules/brand-product-category public brand surface', status: 'production' },
  { prefix: '/api/v2/brands',     owner: 'services/api/src/modules/brand-registry', status: 'production' },
  { prefix: '/api/v2/brand-product-categories', owner: 'services/api/src/modules/brand-product-category', status: 'production' },
  { prefix: '/api/v2/brand-sites', owner: 'services/api/src/modules/brand-registry', status: 'production' },
  { prefix: '/api/v2/sites',      owner: 'services/api/src/modules/brand-registry public site catalog surface', status: 'production' },
  { prefix: '/api/v2/contracts',  owner: 'server/modules/contracts',        status: 'production' },
  { prefix: '/api/v2/diagnosis',  owner: 'services/api/src/modules/diagnosis', status: 'production' },
  { prefix: '/api/v2/file-artifact', owner: 'services/api/src/modules/file-artifact', status: 'production' },
  { prefix: '/api/v2/growth',     owner: 'services/api/src/modules/growth', status: 'production' },
  { prefix: '/api/v2/design/projects', owner: 'server/modules/design', nestjsOwner: 'services/api/src/modules/design', status: 'production' },
  { prefix: '/api/v2/health',     owner: 'server/modules/health',                                                              status: 'production' },
  { prefix: '/api/v2/lifecycle',  owner: 'services/api/src/modules/lifecycle', status: 'production' },
  { prefix: '/api/v2/product-catalog', owner: 'services/api/src/modules/product-catalog', status: 'production' },
  { prefix: '/api/v2/rysnova-bim',   owner: 'server/modules/rysnova-bim',   nestjsOwner: 'services/api/src/modules/rysnova-bim',   status: 'production' },
  { prefix: '/api/v2/system-packs', owner: 'server/modules/system-packs',                                                   status: 'production' },
  { prefix: '/api/v2/analytics',  owner: 'server/modules/analytics',  nestjsOwner: 'services/api/src/modules/analytics',  status: 'production' },
  { prefix: '/api/v2/governance', owner: 'server/modules/governance', nestjsOwner: 'services/api/src/modules/governance', status: 'production' },
  { prefix: '/api/v2/quotation',  owner: 'services/api/src/modules/quote', status: 'production' },
  { prefix: '/api/v2/react-candidate', owner: 'server/modules/v2 react candidate status', status: 'production-candidate' },
  { prefix: '/api/v2/design', owner: 'server/modules/react-candidate/design-candidate.routes', status: 'production-candidate' },
  { prefix: '/api/v2/devices', owner: 'server/modules/react-candidate/devices-candidate.routes', status: 'production-candidate' },
  { prefix: '/api/v2/projects', owner: 'server/modules/react-candidate/projects-candidate.routes', status: 'production-candidate' },
  { prefix: '/api/health', owner: 'server/routes/ops-runtime.routes', status: 'legacy-compat' },
  { prefix: '/api/crm', owner: 'server/routes/crm', status: 'legacy-compat' },
  { prefix: '/api/customers', owner: 'server/routes/core-api legacy customer intake', status: 'legacy-compat' },
  { prefix: '/api/search', owner: 'server/routes/core-api legacy customer search', status: 'legacy-compat' },
  { prefix: '/api/house-types', owner: 'server/routes/core-api legacy house-type library', status: 'legacy-compat' },
  { prefix: '/api/products', owner: 'server/routes/products', status: 'legacy-compat' },
  { prefix: '/api/products/price', owner: 'server/routes/design-runtime.routes', status: 'legacy-compat' },
  { prefix: '/api/projects', owner: 'server/routes/projects', status: 'legacy-compat' },
  { prefix: '/api/devices', owner: 'server/routes/devices', status: 'legacy-compat' },
  { prefix: '/api/design', owner: 'server/routes/design and legacy inline design endpoints', status: 'legacy-compat' },
  { prefix: '/api/pain-diagnosis', owner: 'server/routes/core-api legacy diagnosis', status: 'legacy-compat' },
  { prefix: '/api/solution-match', owner: 'server/routes/core-api legacy solution matching', status: 'legacy-compat' },
  { prefix: '/api/ai-consultant', owner: 'server/routes/core-api legacy AI consultant', status: 'legacy-compat' },
  { prefix: '/api/ai', owner: 'server/routes/ai-assistant and server/routes/ops-runtime.routes', status: 'legacy-compat' },
  { prefix: '/api/quotation', owner: 'server/routes/quotations and server/routes/front-office-runtime.routes', status: 'legacy-compat' },
  { prefix: '/api/quotation-v2', owner: 'server/routes/quotation-v2', status: 'legacy-compat' },
  { prefix: '/api/quotations', owner: 'server/routes/quotations', status: 'legacy-compat' },
  { prefix: '/api/workflows', owner: 'server/routes/workflows', status: 'legacy-compat' },
  { prefix: '/api/workorders', owner: 'server/routes/workorders', status: 'legacy-compat' },
  { prefix: '/api/workorders/create-from-diagnosis', owner: 'server/routes/content-sales.routes', status: 'legacy-compat' },
  { prefix: '/api/construction', owner: 'server/routes/construction', status: 'legacy-compat' },
  { prefix: '/api/materials', owner: 'server/routes/materials', status: 'legacy-compat' },
  { prefix: '/api/hotwater', owner: 'server/routes/hotwater', status: 'legacy-compat' },
  { prefix: '/api/marketing', owner: 'server/routes/marketing', status: 'legacy-compat' },
  { prefix: '/api/contracts', owner: 'server/routes/contracts and legacy inline contract endpoints', status: 'legacy-compat' },
  { prefix: '/api/exports', owner: 'server/routes/exports', status: 'legacy-compat' },
  { prefix: '/api/export', owner: 'server/routes/core-api and legacy export endpoints', status: 'legacy-compat' },
  { prefix: '/api/reports', owner: 'server/routes/reports', status: 'legacy-compat' },
  { prefix: '/api/drawings', owner: 'server/routes/reports/drawings legacy mount', status: 'legacy-compat' },
  { prefix: '/api/dxf', owner: 'server/routes/dxfRoutes', status: 'legacy-compat' },
  { prefix: '/api/rysnova-bim', owner: 'server/routes/rysnova-bim and smart-routing legacy mounts', status: 'legacy-compat' },
  { prefix: '/api/rysnova-bim-bim', owner: 'server/routes/core-api and legacy inline BIM endpoints', status: 'legacy-compat' },
  { prefix: '/api/rysnova-bim/design-workflow', owner: 'server/routes/rysnova-bim-runtime.routes', status: 'legacy-compat' },
  { prefix: '/api/rysnova-bim/calculation', owner: 'server/routes/rysnova-bim-runtime.routes', status: 'legacy-compat' },
  { prefix: '/api/rysnova-bim/code-check', owner: 'server/routes/rysnova-bim-runtime.routes', status: 'legacy-compat' },
  { prefix: '/api/rysnova-bim/bim-integration', owner: 'server/routes/rysnova-bim-runtime.routes', status: 'legacy-compat' },
  { prefix: '/api/rysnova-bim/clash-detection', owner: 'server/routes/rysnova-bim-runtime.routes', status: 'legacy-compat' },
  { prefix: '/api/rysnova-bim-bim/multi-discipline', owner: 'server/routes/rysnova-bim-runtime.routes', status: 'legacy-compat' },
  { prefix: '/api/rysnova-bim-bim/projects', owner: 'server/routes/rysnova-bim-runtime.routes and server/routes/core-api', status: 'legacy-compat' },
  { prefix: '/api/rysnova-bim-bim/cfd-simulation', owner: 'server/routes/rysnova-bim-runtime.routes', status: 'legacy-compat' },
  { prefix: '/api/bim', owner: 'server/routes/bim-export', status: 'legacy-compat' },
  { prefix: '/api/revit', owner: 'server/routes/revit-integration', status: 'legacy-compat' },
  { prefix: '/api/calc', owner: 'server/routes/calculation-api', status: 'legacy-compat' },
  { prefix: '/api/oneclick', owner: 'server/routes/oneclick-api', status: 'legacy-compat' },
  { prefix: '/api/three-tier', owner: 'server/routes/threeTier', status: 'legacy-compat' },
  { prefix: '/api/package', owner: 'server/routes/packagePurchase', status: 'legacy-compat' },
  { prefix: '/api/delivery', owner: 'server/routes/delivery', status: 'legacy-compat' },
  { prefix: '/api/channel', owner: 'server/modules/legacy-api/channel.routes', status: 'legacy-compat' },
  { prefix: '/api/ppt-export', owner: 'server/modules/legacy-api/ppt-export.routes', status: 'legacy-compat' },
  { prefix: '/api/v9', owner: 'server/modules/legacy-api/v9.routes', status: 'production-candidate' },
  { prefix: '/api/admin', owner: 'server/routes/admin.routes and legacy admin guard', status: 'legacy-compat' },
  { prefix: '/api/supreme', owner: 'server/routes/supreme-api', status: 'legacy-compat' },
  { prefix: '/api/standards', owner: 'server/routes/standards.routes', status: 'legacy-compat' },
  { prefix: '/api/closed-loop', owner: 'server/routes/closed-loop.routes', status: 'legacy-compat' },
  { prefix: '/api/enterprise-loop', owner: 'server/routes/enterprise-loop.routes', status: 'legacy-compat' },
  { prefix: '/api/quick-session', owner: 'server/routes/front-office-runtime.routes', status: 'legacy-compat' },
  { prefix: '/api/device-selection', owner: 'server/routes/design-runtime.routes', status: 'legacy-compat' },
  { prefix: '/api/load-calculation', owner: 'server/routes/design-runtime.routes', status: 'legacy-compat' },
  { prefix: '/api/ai-matching', owner: 'server/routes/design-runtime.routes', status: 'legacy-compat' },
  { prefix: '/api/template-library', owner: 'server/routes/design-runtime.routes', status: 'legacy-compat' },
  { prefix: '/api/drawing-sync', owner: 'server/routes/design-runtime.routes', status: 'legacy-compat' },
  { prefix: '/api/content', owner: 'server/routes/content-sales.routes', status: 'legacy-compat' },
  { prefix: '/api/sales', owner: 'server/routes/content-sales.routes', status: 'legacy-compat' },
  { prefix: '/api/diagnosis', owner: 'server/routes/content-sales.routes', status: 'legacy-compat' },
  { prefix: '/api/energy', owner: 'server/routes/energy-carbon.routes', status: 'legacy-compat' },
  { prefix: '/api/carbon', owner: 'server/routes/energy-carbon.routes', status: 'legacy-compat' },
  { prefix: '/api/system', owner: 'server/routes/platform-runtime.routes', status: 'legacy-compat' },
  { prefix: '/api/cache', owner: 'server/routes/platform-runtime.routes', status: 'legacy-compat' },
  { prefix: '/api/agent', owner: 'server/routes/platform-runtime.routes and server/routes/core-api', status: 'legacy-compat' },
  { prefix: '/api/performance', owner: 'server/routes/platform-runtime.routes', status: 'legacy-compat' },
  { prefix: '/api/heartbeat', owner: 'server/routes/design-runtime.routes', status: 'legacy-compat' },
  { prefix: '/api/templates', owner: 'server/routes/front-office-runtime.routes and server/routes/ops-runtime.routes', status: 'legacy-compat' },
  { prefix: '/api/visualization', owner: 'server/routes/core-api and legacy visualization endpoints', status: 'legacy-compat' },
  { prefix: '/api/visuals', owner: 'server/routes/front-office-runtime.routes', status: 'legacy-compat' },
  { prefix: '/api/field-state', owner: 'server/routes/front-office-runtime.routes', status: 'legacy-compat' },
  { prefix: '/api/cad', owner: 'server/routes/front-office-runtime.routes', status: 'legacy-compat' },
  { prefix: '/api/floorplan', owner: 'server/routes/front-office-runtime.routes', status: 'legacy-compat' },
  { prefix: '/api/knowledge-base', owner: 'server/routes/front-office-runtime.routes', status: 'legacy-compat' },
  { prefix: '/api/collaboration', owner: 'server/routes/front-office-runtime.routes and server/routes/ops-runtime.routes', status: 'legacy-compat' },
  { prefix: '/api/econet', owner: 'server/routes/econet.routes', status: 'legacy-compat' },
  { prefix: '/api/tech-support', owner: 'server/routes/tech-support.routes', status: 'legacy-compat' },
  { prefix: '/api/monitor', owner: 'server/routes/ops-runtime.routes', status: 'legacy-compat' },
  { prefix: '/api/backup', owner: 'server/routes/ops-runtime.routes', status: 'legacy-compat' },
  { prefix: '/api/backups', owner: 'server/modules/legacy-api/new-features.routes legacy backup list', status: 'legacy-compat' },
  { prefix: '/api/qa', owner: 'server/routes/qa.routes and legacy QA endpoints', status: 'legacy-compat' },
  { prefix: '/api/promotions', owner: 'server/routes/promotion.routes', status: 'legacy-compat' },
  { prefix: '/api/promotion', owner: 'server/routes/business-domain legacy promotion endpoints', status: 'legacy-compat' },
  { prefix: '/api/journey', owner: 'server/routes/journey.routes', status: 'legacy-compat' },
  { prefix: '/api/dashboard', owner: 'server/routes/business-domain legacy dashboard endpoints', status: 'legacy-compat' },
  { prefix: '/api/quote', owner: 'server/routes/business-domain legacy quote endpoints', status: 'legacy-compat' },
  { prefix: '/api/pricing', owner: 'server/routes/business-domain legacy pricing endpoints', status: 'legacy-compat' },
  { prefix: '/api/material', owner: 'server/routes/business-domain legacy material endpoints', status: 'legacy-compat' },
  { prefix: '/api/acceptance', owner: 'server/routes/business-domain legacy acceptance endpoints', status: 'legacy-compat' },
  { prefix: '/api/settlement', owner: 'server/routes/business-domain legacy settlement endpoints', status: 'legacy-compat' },
  { prefix: '/api/location', owner: 'server/routes/field-services legacy location endpoints', status: 'legacy-compat' },
  { prefix: '/api/doas', owner: 'server/routes/doas-compliance legacy DOAS endpoints', status: 'legacy-compat' },
  { prefix: '/api/operation', owner: 'server-production.js legacy operation endpoints', status: 'legacy-compat' },
  { prefix: '/api/device-positioning', owner: 'server/routes/field-services legacy device-positioning endpoints', status: 'legacy-compat' },
  { prefix: '/api/evolution', owner: 'server/routes/governance-runtime.routes', status: 'legacy-compat' },
  { prefix: '/api/coordination', owner: 'server/routes/air-control legacy coordination endpoints', status: 'legacy-compat' },
  { prefix: '/api/reheat', owner: 'server/routes/air-control legacy reheat endpoints', status: 'legacy-compat' },
  { prefix: '/api/workflow', owner: 'server/routes/governance-runtime.routes', status: 'legacy-compat' },
  { prefix: '/api/self-check', owner: 'server/routes/governance-runtime.routes', status: 'legacy-compat' },
  { prefix: '/api/voice-interaction', owner: 'server-production.js legacy voice interaction endpoints', status: 'legacy-compat' },
  { prefix: '/api/engines', owner: 'server/routes/core-api legacy engine health endpoint', status: 'legacy-compat' },
  { prefix: '/api/image', owner: 'server/modules/legacy-api/new-features.routes legacy image recognition', status: 'legacy-compat' },
  { prefix: '/api/ai-validation', owner: 'server/routes/front-office-runtime.routes', status: 'legacy-compat' },
  { prefix: '/api/feedback', owner: 'server/routes/front-office-runtime.routes', status: 'legacy-compat' },
  { prefix: '/', owner: 'server-production.js root landing page', status: 'legacy-compat' },
  { prefix: '/pain-diagnosis', owner: 'server-production.js legacy web alias', status: 'legacy-compat' },
  { prefix: '/quality-dashboard', owner: 'server-production.js legacy web alias', status: 'legacy-compat' },
  { prefix: '/solution-summary', owner: 'server-production.js legacy web alias', status: 'legacy-compat' },
  { prefix: '/voice-interaction', owner: 'server-production.js legacy web alias', status: 'legacy-compat' },
  { prefix: '/designer', owner: 'server-production.js legacy web alias', status: 'legacy-compat' },
  { prefix: '/sales', owner: 'server-production.js legacy web alias', status: 'legacy-compat' },
  { prefix: '/solution-view', owner: 'server-production.js legacy web alias', status: 'legacy-compat' },
  { prefix: '/admin', owner: 'server-production.js legacy web alias', status: 'legacy-compat' },
  { prefix: '/admin.html', owner: 'server-production.js legacy web alias', status: 'legacy-compat' },
  { prefix: '/store-admin', owner: 'server-production.js legacy web alias', status: 'legacy-compat' },
  { prefix: '/hq-admin', owner: 'server-production.js legacy web alias', status: 'legacy-compat' },
  { prefix: '/customers', owner: 'server-production.js legacy web alias', status: 'legacy-compat' },
  { prefix: '/solutions', owner: 'server-production.js legacy web alias', status: 'legacy-compat' },
  { prefix: '/quotations', owner: 'server-production.js legacy web alias', status: 'legacy-compat' },
  { prefix: '/products', owner: 'server-production.js legacy web alias', status: 'legacy-compat' },
  { prefix: '/analytics', owner: 'server-production.js legacy web alias', status: 'legacy-compat' },
  { prefix: '/settings', owner: 'server-production.js legacy web alias', status: 'legacy-compat' },
  { prefix: '/notifications', owner: 'server-production.js legacy web alias', status: 'legacy-compat' },
  { prefix: '/messages', owner: 'server-production.js legacy web alias', status: 'legacy-compat' },
  { prefix: '/help', owner: 'server-production.js legacy web alias', status: 'legacy-compat' },
  { prefix: '/login', owner: 'server-production.js legacy web alias', status: 'legacy-compat' },
  { prefix: '/mobile', owner: 'server-production.js legacy web alias', status: 'legacy-compat' }
];

const ROUTE_FILE_OWNERSHIP = [
  { file: 'server/modules/audit/audit.routes.js', owner: 'server/modules/audit', status: 'production', mountPrefix: '/api/v2/audit' },
  { file: 'server/modules/contracts/contracts.routes.js', owner: 'server/modules/contracts', status: 'production', mountPrefix: '/api/v2/contracts' },
  { file: 'server/modules/design/design.routes.js', owner: 'server/modules/design', status: 'production', mountPrefix: '/api/v2/design' },
  { file: 'server/modules/health/health.routes.js', owner: 'server/modules/health', status: 'production', mountPrefix: '/api/v2/health' },
  { file: 'server/modules/rysnova-bim/rysnova-bim.routes.js', owner: 'server/modules/rysnova-bim', status: 'production', mountPrefix: '/api/v2/rysnova-bim' },
  { file: 'server/modules/system-packs/system-packs.routes.js', owner: 'server/modules/system-packs', status: 'production', mountPrefix: '/api/v2/system-packs' },
  { file: 'server/modules/analytics/analytics.routes.js', owner: 'server/modules/analytics', status: 'production', mountPrefix: '/api/v2/analytics' },
  { file: 'server/modules/governance/governance.routes.js', owner: 'server/modules/governance', status: 'production', mountPrefix: '/api/v2/governance' },
  { file: 'server/modules/react-candidate/design-candidate.routes.js', owner: 'server/modules/react-candidate', status: 'production-candidate', mountPrefix: '/api/v2/design' },
  { file: 'server/modules/react-candidate/devices-candidate.routes.js', owner: 'server/modules/react-candidate', status: 'production-candidate', mountPrefix: '/api/v2/devices' },
  { file: 'server/modules/react-candidate/projects-candidate.routes.js', owner: 'server/modules/react-candidate', status: 'production-candidate', mountPrefix: '/api/v2/projects' },
  { file: 'server/routes/projects.js', owner: 'server/routes/projects', status: 'legacy-compat', mountPrefix: '/api/projects' },
  { file: 'server/routes/devices.js', owner: 'server/routes/devices', status: 'legacy-compat', mountPrefix: '/api/devices' },
  { file: 'server/routes/design.js', owner: 'server/routes/design', status: 'legacy-compat', mountPrefix: '/api/design' },
  { file: 'server/routes/construction.js', owner: 'server/routes/construction', status: 'legacy-compat', mountPrefix: '/api/construction' },
  { file: 'server/routes/workorders.js', owner: 'server/routes/workorders', status: 'legacy-compat', mountPrefix: '/api/workorders' },
  { file: 'server/routes/workflows.js', owner: 'server/routes/workflows', status: 'legacy-compat', mountPrefix: '/api/workflows' },
  { file: 'server/routes/materials.js', owner: 'server/routes/materials', status: 'legacy-compat', mountPrefix: '/api/materials' },
  { file: 'server/routes/quotations.js', owner: 'server/routes/quotations', status: 'legacy-compat', mountPrefix: '/api/quotations' },
  { file: 'server/routes/quotation-v2.js', owner: 'server/routes/quotation-v2', status: 'legacy-compat', mountPrefix: '/api/quotation-v2' },
  { file: 'server/routes/products.js', owner: 'server/routes/products', status: 'legacy-compat', mountPrefix: '/api/products' },
  { file: 'server/routes/hotwater.js', owner: 'server/routes/hotwater', status: 'legacy-compat', mountPrefix: '/api/hotwater' },
  { file: 'server/routes/marketing.js', owner: 'server/routes/marketing', status: 'legacy-compat', mountPrefix: '/api/marketing' },
  { file: 'server/routes/ai-assistant.js', owner: 'server/routes/ai-assistant', status: 'legacy-compat', mountPrefix: '/api/ai' },
  { file: 'server/routes/bim-export.js', owner: 'server/routes/bim-export', status: 'legacy-compat', mountPrefix: '/api/bim' },
  { file: 'server/routes/revit-integration.js', owner: 'server/routes/revit-integration', status: 'legacy-compat', mountPrefix: '/api/revit' },
  { file: 'server/routes/exports.js', owner: 'server/routes/exports', status: 'legacy-compat', mountPrefix: '/api/exports' },
  { file: 'server/routes/supreme-api.js', owner: 'server/routes/supreme-api', status: 'legacy-compat', mountPrefix: '/api/supreme' },
  { file: 'server/routes/rysnova-bim.js', owner: 'server/routes/rysnova-bim', status: 'legacy-compat', mountPrefix: '/api/rysnova-bim' },
  { file: 'server/routes/rysnova-bim-simple.js', owner: 'server/routes/rysnova-bim-simple', status: 'legacy-compat', mountPrefix: '/api/rysnova-bim' },
  { file: 'server/routes/calculation-api.js', owner: 'server/routes/calculation-api', status: 'legacy-compat', mountPrefix: '/api/calc' },
  { file: 'server/routes/oneclick-api.js', owner: 'server/routes/oneclick-api', status: 'legacy-compat', mountPrefix: '/api/oneclick' },
  { file: 'server/routes/threeTier.js', owner: 'server/routes/threeTier', status: 'legacy-compat', mountPrefix: '/api/three-tier' },
  { file: 'server/routes/packagePurchase.js', owner: 'server/routes/packagePurchase', status: 'legacy-compat', mountPrefix: '/api/package' },
  { file: 'server/routes/crm.js', owner: 'server/routes/crm', status: 'legacy-compat', mountPrefix: '/api/crm' },
  { file: 'server/routes/customQuotation.js', owner: 'server/routes/customQuotation', status: 'legacy-compat', mountPrefix: '/api/quotation' },
  { file: 'server/routes/delivery.js', owner: 'server/routes/delivery', status: 'legacy-compat', mountPrefix: '/api/delivery' },
  { file: 'server/routes/reports.js', owner: 'server/routes/reports', status: 'legacy-compat', mountPrefix: '/api/reports' },
  { file: 'server/routes/drawings.js', owner: 'server/routes/drawings', status: 'legacy-compat', mountPrefix: '/api/drawings' },
  { file: 'server/routes/contracts.js', owner: 'server/routes/contracts', status: 'legacy-compat', mountPrefix: '/api/contracts' },
  { file: 'server/routes/business-domain.js', owner: 'server/routes/business-domain', status: 'legacy-compat', mountPrefix: '/' },
  { file: 'server/routes/core-api.js', owner: 'server/routes/core-api', status: 'legacy-compat', mountPrefix: '/' },
  { file: 'server/routes/rysnova-bim-runtime.routes.js', owner: 'server/routes/rysnova-bim-runtime.routes', status: 'legacy-compat', mountPrefix: '/' },
  { file: 'server/routes/front-office-runtime.routes.js', owner: 'server/routes/front-office-runtime.routes', status: 'legacy-compat', mountPrefix: '/' },
  { file: 'server/routes/ops-runtime.routes.js', owner: 'server/routes/ops-runtime.routes', status: 'legacy-compat', mountPrefix: '/' },
  { file: 'server/routes/governance-runtime.routes.js', owner: 'server/routes/governance-runtime.routes', status: 'legacy-compat', mountPrefix: '/' },
  { file: 'server/routes/dxfRoutes.js', owner: 'server/routes/dxfRoutes', status: 'legacy-compat', mountPrefix: '/api/dxf' },
  { file: 'server/routes/qa.routes.js', owner: 'server/routes/qa.routes', status: 'legacy-compat', mountPrefix: '/api/qa' },
  { file: 'server/routes/promotion.routes.js', owner: 'server/routes/promotion.routes', status: 'legacy-compat', mountPrefix: '/api/promotions' },
  { file: 'server/routes/journey.routes.js', owner: 'server/routes/journey.routes', status: 'legacy-compat', mountPrefix: '/api/journey' },
  { file: 'server/routes/admin.routes.js', owner: 'server/routes/admin.routes', status: 'legacy-compat', mountPrefix: '/api/admin' },
  { file: 'server/routes/page-aliases.js', owner: 'server/routes/page-aliases', status: 'legacy-compat', mountPrefix: '/' },
  { file: 'server/routes/design-runtime.routes.js', owner: 'server/routes/design-runtime.routes', status: 'legacy-compat', mountPrefix: '/' },
  { file: 'server/routes/content-sales.routes.js', owner: 'server/routes/content-sales.routes', status: 'legacy-compat', mountPrefix: '/' },
  { file: 'server/routes/energy-carbon.routes.js', owner: 'server/routes/energy-carbon.routes', status: 'legacy-compat', mountPrefix: '/' },
  { file: 'server/routes/platform-runtime.routes.js', owner: 'server/routes/platform-runtime.routes', status: 'legacy-compat', mountPrefix: '/' },
  { file: 'server/routes/field-services.js', owner: 'server/routes/field-services', status: 'legacy-compat', mountPrefix: '/' },
  { file: 'server/routes/doas-compliance.js', owner: 'server/routes/doas-compliance', status: 'legacy-compat', mountPrefix: '/' },
  { file: 'server/routes/air-control.js', owner: 'server/routes/air-control', status: 'legacy-compat', mountPrefix: '/' },
  { file: 'server/modules/legacy-api/new-features.routes.js', owner: 'server/modules/legacy-api/new-features.routes', status: 'legacy-compat', mountPrefix: '/api' },
  { file: 'server/modules/legacy-api/channel.routes.js', owner: 'server/modules/legacy-api/channel.routes', status: 'legacy-compat', mountPrefix: '/api/channel' },
  { file: 'server/modules/legacy-api/ppt-export.routes.js', owner: 'server/modules/legacy-api/ppt-export.routes', status: 'legacy-compat', mountPrefix: '/api/ppt-export' },
  { file: 'server/modules/legacy-api/v9.routes.js', owner: 'server/modules/legacy-api/v9.routes', status: 'production-candidate', mountPrefix: '/api/v9' }
];

function getRouteOwner(routePath = '') {
  const normalized = routePath.startsWith('/') ? routePath : `/${routePath}`;
  return ROUTE_OWNERSHIP
    .filter(entry => normalized === entry.prefix || normalized.startsWith(`${entry.prefix}/`))
    .sort((a, b) => b.prefix.length - a.prefix.length)[0] || {
      prefix: null,
      owner: 'unassigned',
      status: 'needs-owner'
    };
}

function getRouteOwnerForRoute(route = {}) {
  const byPath = getRouteOwner(route.path);
  if (byPath.status !== 'needs-owner' && byPath.prefix !== '/') return byPath;

  const byFile = ROUTE_FILE_OWNERSHIP.find(entry => entry.file === route.file);
  if (!byFile) return byPath;

  return {
    prefix: byFile.mountPrefix,
    owner: byFile.owner,
    status: byFile.status,
    inferredFromFile: true
  };
}

module.exports = {
  ROUTE_OWNERSHIP,
  ROUTE_FILE_OWNERSHIP,
  getRouteOwner,
  getRouteOwnerForRoute
};
